### PR TITLE
edit logbook

### PR DESCRIPTION
**Pull request by blackbianca**

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi @blackbianca 
Did you intentionally closed this PR?

**Comment by blackbianca** [comment]
I closed it by accident actually. But then I did not reopen it because I didn't want to cause too much trouble

**Review by maxnoe — APPROVED** [review]

**Comment by maxnoe** [comment]
@blackbianca Not much trouble ;)

**Comment by vuillaut** [comment]
> I closed it by accident actually. But then I did not reopen it because I didn't want to cause too much trouble

No trouble there, thanks for contributing.

**Pull request merged**
