### PR TITLE
Add Scipy tutorial material

### PR DESCRIPTION
**Pull request by adonath**
This PR add the material for the Scipy hands on tutorial.

### CODE REVIEW

**Comment by maxnoe** [comment]
@adonath I think we can just remove the flake8 check, it doesn't really make sense to check the whole repo

**Comment by vuillaut** [comment]
It seems like some import are missing in some of the solutions

**Comment by maxnoe** [comment]
@vuillaut these solutions are not scripts,  but snippets to be loaded into the notebook

**Comment by maxnoe** [comment]
@adonath can you maybe also replace the randomstate with the new api for consistency with the other lectures?

**Comment by JulienPeloton** [comment]
Concerning the snippets - one could add `# flake8: noqa` at the top of each snippet if they are not intended to be scanned at all (brute force I reckon).

**Comment by adonath** [comment]
Thanks @maxnoe  and @JulienPeloton, I changed to the new Numpy random API and skipped the PEP8 check for the code snippets.

**Review by vuillaut — APPROVED** [review]

**Pull request merged**
