### PR TITLE
Added my sign off to the logbook

### PR DESCRIPTION
**Pull request by GabrielF98**
Thanks so much to all of you this is the best school I have attended.

### CODE REVIEW

**Review by maxnoe — CHANGES_REQUESTED** [review]
High, thanks, but you added many unnecessary files here. See the files tab here on github.

**Comment by GabrielF98** [comment]
Hi Max,

Sorry about this, what’s the best way to remove these files I seem to be having trouble

Thanks,

Gabriel

**Comment by JulienPeloton** [comment]
Hi @GabrielF98 -- if you want to keep those files on your machine, but removing them from the index, you would use for example:

```bash
git rm --cached <unnecessary filename>
```

**Comment by GabrielF98** [comment]
I think I have done this now?

**Comment by JulienPeloton** [comment]
No - you removed the change on the logbook (what is relevant), but unwanted files are still there (see the tab `Files changed`). You could do:

```bash
# remove from index unnecessary files
git rm --cached .DS_Store
git rm --cached  "machine-learning-1/Dimensionality Reduction.ipynb"
git rm --cached  "machine-learning-2/Validation and Optimization.ipynb"

git commit -m "remove unwanted files"

# add your contribution to the logbook (assuming you still have the changes)
git add participants_logbook.md

# commit and push
git commit -m "Add my contribution to the logbook"
git push
```

**Comment by GabrielF98** [comment]
Ok Ive run those how does it look at your end now?

Sorry about this and thanks for your help Julien

**Comment by JulienPeloton** [comment]
No - the unwanted files are still there, and your contribution to the logbook is no more here.

**Pull request closed without merging**
