### PR TITLE
Add Scikit-HEP lecture

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hello @vuillaut, all, this is the whole lectuure material module minor tweaks that may come in during the day. I have updated the conda environment.yml file. If anyone can check the trivial instructions on the README and confirm that they can run some files, then great. I have tested things on Binder. Advance thanks.

**Review by vuillaut — APPROVED** [review]
thanks

Shall we require participants to prepare the env in advance (during lunch break)?

**Comment by eduardo-rodrigues** [comment]
> Shall we require participants to prepare the env in advance (during lunch break)?

That's probably better, yes, just in case, though they will have time to have the env created while I go through my "slides", which are the first 2 notebooks.

BTW, I will be running things myself with Binder - would have been just fine locally for everything except for the part that requires various TF related packages, as not all is available for Windows. Shouldn't be a problem.

**Comment by eduardo-rodrigues** [comment]
Happy for this to be merged. I can't do it. Thanks.

**Pull request merged**
